[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "postgresql"]

[phases.install]
cmds = [
    "rm -rf node_modules/.cache || true",
    "rm -rf .next || true", 
    "npm ci --no-optional --prefer-offline --no-audit --no-fund",
]

[phases.build]
cmds = [
    "rm -rf node_modules/.cache || true",
    "npm run build",
]

[start]
cmd = "node scripts/start-with-db.js"

[variables]
NPM_CONFIG_CACHE = "/tmp/.npm"
CYPRESS_CACHE_FOLDER = "/tmp/.cypress"
CYPRESS_INSTALL_BINARY = "0"
CYPRESS_SKIP_BINARY_INSTALL = "true"
NODE_ENV = "production" 