[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "postgresql"]

[phases.install]
cmds = [
    "npm ci --no-optional --prefer-offline --no-audit --no-fund",
]

[phases.build]
cmds = [
    "npm run build",
]

[start]
cmd = "npm run start"

[variables]
NPM_CONFIG_CACHE = "/tmp/.npm"
CYPRESS_CACHE_FOLDER = "/tmp/.cypress"
NODE_ENV = "production" 